# Generated by Django 5.1.1 on 2024-09-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_productentry_delete_moodentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productentry",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
